name: Create NPM Changelog + Version + Release + Publish
on:
  workflow_call:

jobs:
  release:
    name: Create NPM Changelog + Version + Release + Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org'

      - name: Generate changelog and calculate version number
        id: changelog
        uses: TriPSs/conventional-changelog-action@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          version-file: ./package.json
          skip-commit: true
          skip-tag: true
          skip-on-empty: true
          skip-version-file: true
          output-file: ./CHANGELOG.md

      - name: "NPM: Install"
        if: ${{ steps.changelog.outputs.tag }}
        run: npm ci

      - name: "NPM: build"
        if: ${{ steps.changelog.outputs.tag }}
        run: npm run build

      - name: "NPM: version"
        if: ${{ steps.changelog.outputs.tag }}
        run: npm version ${{ steps.changelog.outputs.version }} --no-commit-hooks --no-git-tag-version

      - name: "commit changes and add tag"
        uses: EndBug/add-and-commit@v9
        if: ${{ steps.changelog.outputs.tag }}
        with:
          add: |
            - CHANGELOG.md
            - package.json
            - package-lock.json
          tag: ${{ steps.changelog.outputs.tag }}
          message: "chore(release): ${{ steps.changelog.outputs.tag }} [skip ci]"
          push: true

      - name: Create release
        id: release
        if: ${{ steps.changelog.outputs.tag }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.github_token }}
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}

      - name: "NPM: publish"
        if: ${{ steps.changelog.outputs.tag }}
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}