name: Deploy to server

on:
  workflow_call:
    inputs:
      php_version:
        required: False
        type: string
        description: 'PHP version that should be used (default: 8.3)'
        default: '8.3'
      build_tar_artifact_name:
        required: True
        type: string
        description: 'The Name of the artifact file to deploy'
      stage:
        required: true
        type: string
        description: 'Stage to deploy to (Usually staging/testing)'
      ref_name:
        required: true
        type: string
        description: 'Branch name that should be deployed'
      deploy_action:
        required: false
        type: string
        default: 'deploy'
        description: 'Deployer action to run (default: deploy)'
      deployer_version:
        required: false
        type: string
        description: 'Version of deployer to use (default: 7)'
        default: '7'
    secrets:
      private_key:
        required: true

jobs:
  build:
    name: Build Laravel based on php ${{ input.php_version }} and node ${{ inputs.node_version }}
    runs-on: ${{ fromJson(inputs.runnerTag) }}
    steps:

      - name: Setup PHP ${{ inputs.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}

      - name: Download the build
        uses: actions/download-artifact@v3
        with:
          name: ${{ inputs.build_tar_artifact_name }}

      - name: unpack build
        run: tar -xvf ${{ inputs.build_tar_artifact_name }}.tar

      - name: remove build
        run: rm -f ${{ inputs.build_tar_artifact_name }}.tar || true

      - name: Deploy
        uses: deployphp/action@v1
        with:
          private-key: ${{ secrets.private_key }}
          deployer-version: ${{ inputs.deployer_version }}
          dep: ${{ inputs.deploy_action }} stage=${{ inputs.stage }} --branch ${{ inputs.ref_name }} -v

