name: Deploy to server

on:
  workflow_call:
    inputs:
      php_version:
        required: False
        type: string
        description: 'PHP version that should be used (default: 8.3)'
        default: '8.3'
      node_version:
        required: False
        type: string
        description: 'node that should be used (default: 20)'
        default: '20'
      php_tools:
        required: False
        type: string
        description: 'Override php tools (default: composer:2.2)'
        default: 'composer:2'
      runnerTag:
        required: False
        default: "[ 'ubuntu-latest' ]"
        type: string
    secrets:
      auth_json:
        default: ""
        required: false

jobs:
  build:
    name: Build Laravel based on php ${{ input.php_version }} and node ${{ inputs.node_version }}
    runs-on: ${{ fromJson(inputs.runnerTag) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP ${{ inputs.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.php_version }}
          tools: ${{ inputs.php_tools }}

      - name: Setup node ${{ inputs.node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install composer dependencies
        run: composer install --no-scripts --ignore-platform-reqs --no-dev --no-scripts --prefer-dist --no-progress --no-interaction --optimize-autoloader

      - name: install node dependencies
        run: npm install

      - name: build node stuff
        run: npm build

      - name: Tar build files
        run: tar --exclude="node_modules" -cvf laravel.tar ./

      - name: Save Build to artifact
        uses: actions/upload-artifact@v3
        with:
          name: laravel
          path: ./laravel.tar
          retention-days: 0